Vet 56 clients employees add remove
vet-agh/VET pull request #18
Opened 2022-12-07 17:52 UTC by Karicha00

Stworzona została strona internetowa główna Home oraz dwie podstrony - /clients i /employees.
Na głównej stronie znajduje się 6 przycisków, chwilowo 5 z nich wskazuje na /clients, jeden wskazuje na /employees (do zmiany)

Na podstronach znajdują się tabele, w których można przeglądać wszystkich klientów (pracowników), można dodawać nowego klienta(pracownika) oraz usuwać już istniejących

2022-12-07 21:23 UTC, MichSawi commented on frontend/src/App.js
> +            <Route path="/equipments" element={<ClientPage />} />
Tutaj raczej powinno być /equipment bo nigdzie nie użwaliśmy wcześniej equipments

2022-12-08 15:29 UTC, krawczykaghust commented on frontend/src/App.js
>  import { BrowserRouter, Routes, Route} from 'react-router-dom'
Please keep the same style for brackets either {arg, arg} or { arg, arg }

2022-12-08 18:28 UTC, krawczykaghust requested changes
Logic, style, bug fixes to be resolved

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/App.js
> +            <Route path="/"element={<Home />} />
Please check these routes with our routes in backend.

Also in line 18 please add a space before elemnt

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/App.js
> +
Please delete these empty spaces.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/App.js
> +
This space also, not needed

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/components/Navbar.js
> +
Please delete this empty spaces. It is not needed. Keep that in mind throughout the code.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/components/Navbar.js
> +        <header>
We have missing tab here or additional at the bottom. Keep te div structure symmetric

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/App.js
> +      <Navbar />
Please add a tab here as this <Navbar/> is a child component of parent <BrowserRouter>

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/index.css
> +
Please format the css. Keep the same spaces between the elements. Keep the same style for brackets. And stick to one language for class names - we choose English as for code purposes.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/index.css
> +
f.e. about the style. here we have three blank lines, before we had two. Keep it the same.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/index.css
> +przyciski_nawigacji{
Change this to english.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/index.css
> +
Additional space not needed

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/index.css
> +a{
Adjust to the rest of style. Add space before curly brace. Do it with every element in .css

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/views/EmployeeMainPage.js
> +import {useEffect} from 'react'
Keep to one style of brackets. Please

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/views/EmployeeMainPage.js
> +        <input type="submit" value="Wróć do strony głównej" />
Structure of DOM? Close and open elements are not symmetric

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/views/EmployeeMainPage.js
> +                {employees && employees.map((employee) => (
Additional tabs not needed

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/views/EmployeeMainPage.js
> +            </div>
Which div this one closes? Please update the HTML Structure.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/views/Home.js
> +    <input type="submit" value="Zatrudnieni" />
Please change this to Pracownicy

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/views/Home.js
> +    <przyciski_nawigacji>
"The tag <przyciski_nawigacji> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter." Also you create a react component here which isn't defined anywhere.

Fix this.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/views/Home.js
> +    }
This function has empty body.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/components/EmployeeDetails.js
> +             <button onClick={handleClickDelete}>Usuń pracownika</button>
HTML structure

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/components/EmployeeDetails.js
> +            <strong> <p> {employee.imie} { } {employee.nazwisko}</p> </strong>
Please remove empty spaces

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/components/ClientForm.js
> +            </label>
HTML Structure

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/components/EmployeeDetails.js
> +            <p>Data dołączenia do rejestru pracowników: {employee.createdAt}</p>
This .createdAt value (date) should be displayed in readable format. Convert this using datetime object f.e.

2022-12-08 18:28 UTC, krawczykaghust commented on frontend/src/components/EmployeeDetails.js
> +            <p> Numer konta: {employee.numer_konta} </p>
Format int for numer konta as this could be displayed as:

Numer konta: 123456789012345680000
Numer konta: 9.876543210987655e+25

2022-12-08 20:19 UTC, krawczykaghust commented on frontend/src/views/Home.js
> +    <przyciski_nawigacji>
key one

2022-12-08 20:20 UTC, krawczykaghust commented on frontend/src/App.js
> +            <Route path="/"element={<Home />} />
key one

2022-12-08 20:20 UTC, krawczykaghust commented on frontend/src/index.css
> +przyciski_nawigacji{
key one

2022-12-08 20:20 UTC, krawczykaghust commented on frontend/src/views/Home.js
> +    <input type="submit" value="Zatrudnieni" />
key one

2022-12-08 20:21 UTC, krawczykaghust commented on frontend/src/App.js
> +            <Route path="/equipments" element={<ClientPage />} />
key one

2022-12-09 12:41 UTC, krawczykaghust commented
This pull request is no longer valid. This monolith was broken into smaller pull requests.

2022-12-09 12:41 UTC, closed without merging