Vet 58 add employee frontend
vet-agh/VET pull request #23
Opened 2022-12-08 23:54 UTC by Karicha00

Jako użytkownik mam dostęp do strony bazy Employee.
Została stworzona podstrona, w którą można wejść klikając odpowiedni przycisk na stronie głównej (pracownicy).
Wyświetlają się nam wtedy wszyscy pracownicy w całej bazie danych oraz można dodać nowego pracownika wypełniając wszystkie pola a następnie klikając przycisk "Dodaj pracownika"

2022-12-11 09:46 UTC, maclipski requested changes
Kod poprawny, wymagający wyłącznie zmian stylistycznych. Warto poprawić dla zwiększenia czytelności na przyszłość

2022-12-11 09:46 UTC, maclipski commented on frontend/src/components/EmployeeDetails.js
> +            <p>Data dołączenia do rejestru pracowników: {employee.createdAt}</p>
"Data dołączenia do rejestru pracowników" brzmi dziwnie, jakby to pracownik podejmował jakieś działanie "dołączenia" - tego typu sformuowanie bardziej pasuje do zdania "Data dołączenia Polski do NATO" przykładowo. Szczerze zmieniłbym to na "Data dodania do rejestru", po prostu.

2022-12-11 09:46 UTC, maclipski commented on frontend/src/components/EmployeeForm.js
> +import { useEmployeesContext } from '../hooks/useEmployeeContext'
Zachowaj proszę spójność kodu {arg} lub { arg }

2022-12-11 09:46 UTC, maclipski commented on frontend/src/components/EmployeeForm.js
> +                <label> id kliniki: </label>
Mało spójny tytuł (jako jedyny zaczyna się z małej litery i jest dość pokraczny). Zmieniłbym na Numer identyfikacyjny kliniki

2022-12-11 09:46 UTC, maclipski commented on frontend/src/context/EmployeeContext.js
> +        case 'SET_EMPLOYEES':
Formatowanie do poprawy, case powinny być na tej samej wyskości. Dodatkowo zdecyduj się na jedną opcję
return {}
lub 
return{}

2022-12-11 09:46 UTC, maclipski commented on frontend/src/context/EmployeeContext.js
> +        case 'SET_EMPLOYEES':
default na tej samej wysokości co wszystkie case

2022-12-11 09:46 UTC, maclipski commented on frontend/src/context/EmployeeContext.js
> +            {children }
Formatowanie do poprawy {arg} lub { arg }

2022-12-11 09:46 UTC, maclipski commented on frontend/src/hooks/useEmployeeContext.js
> +import { useContext} from "react";
Formatowanie do poprawy {arg} lub { arg }

2022-12-11 09:46 UTC, maclipski commented on frontend/src/index.css
> +
Usuń nadmiarowy enter, wszędzie wcześniej stosujesz pojedynczy

2022-12-11 09:46 UTC, maclipski commented on frontend/src/index.css
> +
Usuń nadmiarowy enter, wszędzie wcześniej stosujesz pojedynczy

2022-12-11 09:46 UTC, maclipski commented on frontend/src/index.css
> +
Usuń nadmiarowy enter, wszędzie wcześniej stosujesz pojedynczy

2022-12-11 09:46 UTC, maclipski commented on frontend/src/views/EmployeeMainPage.js
> +import { useEmployeesContext } from '../hooks/useEmployeeContext'
Ujednolicić nawiasy {arg} lub { arg }

2022-12-13 23:56 UTC, krawczykaghust requested changes
Please pull from origin/develop and handle merge conflicts

2022-12-14 12:23 UTC, maclipski approved these changes
All problems resolved

2022-12-15 20:19 UTC, krawczykaghust approved these changes
Approved

2022-12-15 20:35 UTC, krawczykaghust requested changes
Solve merge conflicts

2022-12-15 20:54 UTC, maclipski approved these changes
Double checked, resolve conflicts and merge

2022-12-15 22:37 UTC, krawczykaghust approved these changes
Approved

2022-12-15 22:37 UTC, merged