VET-64 deleting employee button frontend
vet-agh/VET pull request #24
Opened 2022-12-08 23:56 UTC by Karicha00

Jako użytkownik mam dostęp do strony bazy Employee.
Została stworzona podstrona, w którą można wejść klikając odpowiedni przycisk na stronie głównej (pracownicy).
Wyświetlają się nam wtedy wszyscy pracownicy w całej bazie danych oraz można usunąć pracownika klikając przycisk przy wybranym pracowniku "Usuń pracownika".

2022-12-11 09:53 UTC, maclipski requested changes
Jakbym ten kod już gdzieś widział xd
Do poprawienia

2022-12-11 09:53 UTC, maclipski commented on frontend/src/components/EmployeeDetails.js
> +            <p>Data dołączenia do rejestru pracowników: {employee.createdAt}</p>
Zmieniłbym na "Data dodania do rejestru"

2022-12-11 09:53 UTC, maclipski commented on frontend/src/components/EmployeeForm.js
> +import { useEmployeesContext } from '../hooks/useEmployeeContext'
Nawiasy do ujednolicenia {arg} lub { arg }

2022-12-11 09:53 UTC, maclipski commented on frontend/src/components/EmployeeForm.js
> +                <label> id kliniki: </label>
Zmieniłbym na Numer identyfikacyjny kliniki

2022-12-11 09:53 UTC, maclipski commented on frontend/src/hooks/useEmployeeContext.js
> +import { useContext} from "react";
Nawiasy do ujednolicenia {arg} lub { arg }

2022-12-11 09:53 UTC, maclipski commented on frontend/src/index.css
> +
Usunąć nadmiarowy enter

2022-12-11 09:53 UTC, maclipski commented on frontend/src/index.css
> +
Usunąć nadmiarowy enter

2022-12-11 09:53 UTC, maclipski commented on frontend/src/index.css
> +
Usunąć nadmiarowy enter

2022-12-11 09:53 UTC, maclipski commented on frontend/src/views/EmployeeMainPage.js
> +import { useEmployeesContext } from '../hooks/useEmployeeContext'
Nawiasy do ujednolicenia {arg} lub { arg }

2022-12-11 09:53 UTC, maclipski commented on frontend/src/context/EmployeeContext.js
> +        case 'SET_EMPLOYEES':
Poprawić formatowanie, case i default na jednej wysokości dodatkowo ujednolicić 
return{
lub 
return {

2022-12-13 23:56 UTC, krawczykaghust requested changes
Please pull from origin/develop and handle merge conflicts

2022-12-14 12:27 UTC, maclipski approved these changes
One } to be fixed, the rest solved

2022-12-15 20:55 UTC, maclipski approved these changes
Double checked, resolve conflicts and merge

2022-12-15 22:42 UTC, krawczykaghust approved these changes
Approved

2022-12-15 22:42 UTC, merged