VET-59-AddClient-Frontend
vet-agh/VET pull request #25
Opened 2022-12-09 00:14 UTC by Karicha00

Jako użytkownik mam dostęp do strony bazy Clients.
Została stworzona podstrona, w którą można wejść klikając odpowiedni przycisk na stronie głównej (klienci).
Wyświetlają się nam wtedy wszyscy klienci w całej bazie danych oraz można dodać nowego klienta wypełniając wszystkie pola a następnie klikając przycisk "Dodaj klienta"

2022-12-11 17:45 UTC, maclipski requested changes
Stylistyczne poprawki do wprowadzenia

2022-12-11 17:45 UTC, maclipski commented on frontend/src/components/ClientDetails.js
> +            <p> Numer konta:{client.numer_konta} </p>
Zachowaj jednolity styl kodu
<p>Text</p>
lub
<p> Text </p>

2022-12-11 17:45 UTC, maclipski commented on frontend/src/components/ClientDetails.js
> +            <p>Data dołączenia do rejestru klientów: {client.createdAt}</p>
"Data dodania do rejestru" zamiast "daty dołączenia"

2022-12-11 17:45 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +    const client = {imie, nazwisko, numer_konta, id_pacjenta}
Jednolite nawiasy {arg, arg} lub { arg, arg }

2022-12-11 17:45 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +            <label>  Numer konta (opcjonalne): </label>
Usunąć podwójną spację przed numerem konta

2022-12-11 17:45 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +            <label> id pacjenta: </label>
"Numer identyfikacyjny pacjenta", zamiast id pacjenta

2022-12-11 17:45 UTC, maclipski commented on frontend/src/context/ClientContext.js
> +            {children }
Ujednolicić nawias {arg} lub { arg }

2022-12-13 23:56 UTC, krawczykaghust requested changes
Please pull from origin/develop and handle merge conflicts

2022-12-14 12:30 UTC, maclipski requested changes
Two little things to improve, changes requested

2022-12-14 12:30 UTC, maclipski commented on frontend/src/context/ClientContext.js
> +        return state
\t to add, code not clear

2022-12-14 12:30 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +             onChange={(e) => setNazwisko(e.target.value)}
Unnecessary extra space, del pls

2022-12-15 20:32 UTC, maclipski approved these changes
Everything acceptable, ready to merge

2022-12-15 21:50 UTC, krawczykaghust approved these changes
Approved

2022-12-15 21:50 UTC, merged