VET-65 remove client button frontend
vet-agh/VET pull request #26
Opened 2022-12-09 00:18 UTC by Karicha00

Jako użytkownik mam dostęp do strony bazy Clients.
Została stworzona podstrona, w którą można wejść klikając odpowiedni przycisk na stronie głównej (klienci).
Wyświetlają się nam wtedy wszyscy pracownicy w całej bazie danych oraz można usunąć klienta klikając przycisk przy wybranym kliencie "Usuń klienta".

2022-12-11 17:52 UTC, maclipski requested changes
Zmiany stylistyczne do wprowadzenia

2022-12-11 17:52 UTC, maclipski commented on frontend/src/App.js
> +import ClientPage from './views/ClientMainPage';
Niepotrzebny średnik, zaburza spójność kodu

2022-12-11 17:52 UTC, maclipski commented on frontend/src/components/ClientDetails.js
> +            <p>Data dołączenia do rejestru klientów: {client.createdAt}</p>
"Data dodania do rejestru", zamiast "Daty dołączenia"

2022-12-11 17:52 UTC, maclipski commented on frontend/src/components/ClientDetails.js
> +            <p> Numer konta:{client.numer_konta} </p>
Ujednolicić
<p>Text
lub 
<p> Text

2022-12-11 17:52 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +            <label>  Numer konta (opcjonalne): </label>
Usunąć podwójną spację

2022-12-11 17:52 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +            <label> id pacjenta: </label>
"Numer identyfikacyjny pacjenta", zamiast "id pacjenta"

2022-12-11 17:52 UTC, maclipski commented on frontend/src/context/ClientContext.js
> +
Usunąć nadmiarowe Enter'y

2022-12-11 17:52 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +    {
Ujednolicić nawias, w pozostałej części kodu używana formatka
if {
code
}
zamiast
if
{
code
}

2022-12-11 17:52 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +    {
Ujednolicić nawias, w pozostałej części kodu używana formatka
if {
code
}
zamiast
if
{
code
}

2022-12-13 23:56 UTC, krawczykaghust requested changes
Please pull from origin/develop and handle merge conflicts

2022-12-14 12:33 UTC, maclipski requested changes
Nie na rady no kodzik trzeba poprawić

2022-12-14 12:33 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +    {
Problem dalej nienaprawiony

2022-12-14 12:33 UTC, maclipski commented on frontend/src/components/ClientForm.js
> +    {
Problem dalej nienaprawiony

2022-12-14 12:33 UTC, maclipski commented on frontend/src/context/ClientContext.js
> +        return state
Brak \t przed return, kod nieczytelny

2022-12-15 20:56 UTC, maclipski approved these changes
Double checked, resolve conflicts and merge

2022-12-15 22:17 UTC, krawczykaghust approved these changes
Approved

2022-12-15 22:17 UTC, merged