Vet 63 clinic frontend
vet-agh/VET pull request #32
Opened 2022-12-13 17:31 UTC by Karicha00

Jako użytkownik mam dostęp do strony bazy Clinic.
Została stworzona podstrona, w którą można wejść klikając odpowiedni przycisk na stronie głównej (zakłady).
Wyświetlają się nam wtedy wszystkie zakłady w całej bazie danych oraz można dodać nowy zakład wypełniając wszystkie pola a następnie klikając przycisk "Dodaj zakład"

2022-12-14 00:09 UTC, krawczykaghust requested changes
Review added for VET-69 both versions. Please update it. Also please pull from origin/develop to handle any inconsitents

2022-12-15 21:00 UTC, maclipski requested changes
Refactoring necessary

2022-12-15 21:00 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +            return state
one \t too much, delete it please

2022-12-15 21:00 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +
Delete extra \n

2022-12-15 21:00 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +        }
I'd recommend this return to be oneliner
return { clinics: action.payload }

2022-12-15 21:00 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +        }
I'd recommend this return to be oneliner
return { clinics: [action.payload, ...state.clinics] }

2022-12-15 21:11 UTC, maclipski approved these changes
Cool

2022-12-15 21:17 UTC, krawczykaghust approved these changes
Approved

2022-12-15 21:18 UTC, merged