Vet 69 delete clinic button frontend
vet-agh/VET pull request #33
Opened 2022-12-13 17:33 UTC by Karicha00

Jako użytkownik mam dostęp do strony bazy Clinic.
Została stworzona podstrona, w którą można wejść klikając odpowiedni przycisk na stronie głównej (zakłady).
Wyświetlają się nam wtedy wszystkie zakłady w całej bazie danych oraz można usunąć zakład klikając przycisk przy wybranym zakładzie "Usuń zakład".

2022-12-14 00:05 UTC, krawczykaghust commented on frontend/src/views/ClinicMainPage.js
> +
Please remove empty space

2022-12-14 00:06 UTC, krawczykaghust commented on frontend/src/components/ClinicForm.js
> +            console.log('new clinic added', json)
Please remove console.log statement. It is not needed to be put into the Production. We just use it for development purposes.

2022-12-14 00:08 UTC, krawczykaghust commented on frontend/src/index.js
>      <ScheduleContextProvider>
Here it should be tabbed. Nest these context providers for now (tab after every context like HTML Structure). It will be fixed in the later versions.

2022-12-14 00:09 UTC, krawczykaghust requested changes
Review added for VET-69 both versions. Please update it. Also please pull from origin/develop to handle any inconsitents

2022-12-15 21:04 UTC, maclipski requested changes
Refactoring necessary

2022-12-15 21:04 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +
Extra \n

2022-12-15 21:04 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +            return state
extra \t to be deleted

2022-12-15 21:04 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +        }
oneliner recommended

2022-12-15 21:04 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +        }
oneliner recommended

2022-12-15 21:04 UTC, maclipski commented on frontend/src/context/ClinicContext.js
> +
unnecesary \n and oneliner recommended

2022-12-15 21:12 UTC, maclipski approved these changes
cool

2022-12-15 21:18 UTC, krawczykaghust approved these changes
Approved

2022-12-15 21:23 UTC, merged